apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: testapp33.hlx-dev.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  name: guestbook-ui
spec:
  type: LoadBalancer
  ports:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 80
  selector:
    app: guestbook-ui
